executors:
  app-executor:
    docker:
      - image: cimg/node:16.19
    resource_class: xlarge

  test-executor:
    docker:
      - image: cimg/node:16.19
      - image: mongo:5.0.12
    resource_class: xlarge

parameters:
  gamba-ui:
    type: boolean
    default: false
  deploy-env:
    type: string
    default: dev

aliases:
  - &restore-cache
    restore_cache:
      keys:
        - v1-{{ checksum "yarn.lock" }}

commands:
  job-setup-gamba-ui:
    description: 'Job Setup'
    steps:
      - checkout
      - *restore-cache

jobs:
  lint-gamba-ui:
    executor: app-executor
    steps:
      - job-setup-gamba-ui
      - run:
          name: Lint
          command: npx nx@15.9.2 lint gamba-ui

  test-gamba-ui:
    executor: test-executor
    steps:
      - job-setup-gamba-ui
      - run:
          name: Test
          command: npx nx@15.9.2 test gamba-ui

  build-gamba-ui:
    executor: app-executor
    parameters:
      build-env:
        type: string
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - job-setup-gamba-ui
      - when:
          condition:
            and:
              - not:
                  equal: [production, << parameters.build-env >>]
          steps:
            - run:
                name: Build
                command: npx nx@15.9.2 build gamba-ui
      - when:
          condition:
            equal: [production, << parameters.build-env >>]
          steps:
            - run:
                name: Build
                command: npx nx@15.9.2 build gamba-ui --configuration=production

workflows:
  gamba-ui:
    when: << pipeline.parameters.gamba-ui >>
    jobs:
      - lint-gamba-ui
      - test-gamba-ui
      - build-gamba-ui:
          name: build-environments
          build-env: environments
